PIPE_SPEED = 2
BIRD_ROTATION_MULTIPLIER = 3
GRAVITY = 0.125
PIPE_SPAWN_INTERVAL = 1200
PIPE_SPAWN_LOCATIONS = [x for x in range(200,401)]
BIRD_JUMP_STRENGTH = 4

PIPE_COLOR = 'GREEN'
BIRD_COLOR = 'YELLOW'
TIME = 'DAY'